### ISSUE TITLE
config.include('pyramid_crow') is importing "tests.py"

### ISSUE THREAD

**Issue by buzzijavier** [npilon/pyramid_crow#7]
In my application, when i call `config.include('pyramid_crow')` it calls config.scan() and then that finds tests.py, can you ignore it? I don't install webtests on deployments, on my local sure, but not when i deploy to any other environment.

**Comment by buzzijavier** [comment]
Maybe use `config.scan(ignore='pyramid_crow.tests')` http://docs.pylonsproject.org/projects/pyramid/en/latest/_modules/pyramid/config.html#Configurator.scan  ? or maybe move tests.py outside?

**Comment by npilon** [comment]
Thank you for the bug report! I've released 0.3.1 with your suggested fix; can you confirm that it addresses your issue?

**Comment by buzzijavier** [comment]
Confirmed, works great now, thanks!
